// ===== Combine all topics from individual files =====
// Each topic file defines a TOPIC_XX constant
// Topics are loaded from topics/ folder

const TOPICS = [
    TOPIC_01,
    TOPIC_02,
    TOPIC_03,
    TOPIC_04,
    TOPIC_05,
    TOPIC_06,
    TOPIC_07,
    TOPIC_08,
    TOPIC_09,
    TOPIC_10,
    TOPIC_11,
    TOPIC_12,
    TOPIC_13,
    TOPIC_14,
    TOPIC_15,
    TOPIC_16,
    TOPIC_17,
    TOPIC_18
];

const EXERCISES = [
    { id: 1, topicId: 1, title: "គណនាកុំផ្លិច", difficulty: "easy", problem: "គណនា (3 + 2i) + (1 - 4i)" },
    { id: 2, topicId: 1, title: "គុណកុំផ្លិច", difficulty: "medium", problem: "គណនា (2 + 3i)(1 - i)" },
    { id: 3, topicId: 1, title: "Conjugate", difficulty: "easy", problem: "រក z̄ ប្រសិនបើ z = 5 - 3i" },
    { id: 4, topicId: 1, title: "Modulus", difficulty: "medium", problem: "គណនា |3 + 4i|" },
    { id: 5, topicId: 2, title: "លីមីតសាមញ្ញ", difficulty: "easy", problem: "lim(x→3) (x² - 9)/(x - 3)" },
    { id: 6, topicId: 2, title: "លីមីតអនន្ត", difficulty: "medium", problem: "lim(x→∞) (3x² + 1)/(2x² - 5)" },
    { id: 7, topicId: 2, title: "លីមីត Trig", difficulty: "hard", problem: "lim(x→0) sin(3x)/x" },
    { id: 8, topicId: 3, title: "ភាពជាប់", difficulty: "easy", problem: "ពិនិត្យភាពជាប់ f(x) = (x²-1)/(x-1) នៅ x=1" },
    { id: 9, topicId: 3, title: "ភាពជាប់ Piecewise", difficulty: "medium", problem: "ពិនិត្យភាពជាប់ f(x) = {x² ប្រសិនបើ x≤1, 2x ប្រសិនបើ x&gt;1}" },
    { id: 10, topicId: 4, title: "រកបរមា", difficulty: "easy", problem: "រកបរមា f(x) = x² - 4x + 5" },
    { id: 11, topicId: 4, title: "រកអតិបរមា", difficulty: "medium", problem: "រកអតិបរមា f(x) = -x² + 6x - 5" },
    { id: 12, topicId: 4, title: "លំហាត់អនុវត្តន៍", difficulty: "hard", problem: "រកបរមា/អតិបរមា f(x) = x³ - 3x + 2" },
    { id: 13, topicId: 5, title: "អនុគមន៍សនិទាន", difficulty: "easy", problem: "គណនា 2⁴ · 2³" },
    { id: 14, topicId: 5, title: "អនុគមន៍សនិទាន", difficulty: "medium", problem: "ដោះស្រាយ 3ˣ = 81" },
    { id: 15, topicId: 6, title: "eˣ", difficulty: "easy", problem: "គណនា e⁰ + e¹ + e²" },
    { id: 16, topicId: 6, title: "ដេរីវ៉ាន់ eˣ", difficulty: "medium", problem: "រក d/dx[e^(2x+1)]" },
    { id: 17, topicId: 7, title: "ln(x)", difficulty: "easy", problem: "គណនា ln(e⁵)" },
    { id: 18, topicId: 7, title: "Log", difficulty: "medium", problem: "គណនា log₂(32) + log₃(27)" },
    { id: 19, topicId: 8, title: "អាំងតេក្រាល", difficulty: "easy", problem: "គណនា ∫(2x + 3)dx" },
    { id: 20, topicId: 8, title: "អាំងតេក្រាល Trig", difficulty: "medium", problem: "គណនា ∫sin(x)cos(x)dx" },
    { id: 21, topicId: 8, title: "អាំងតេក្រាលស្មុគស្មាញ", difficulty: "hard", problem: "គណនា ∫x²eˣdx" },
    { id: 22, topicId: 9, title: "អាំងតេក្រាលកំណត់", difficulty: "easy", problem: "គណនា ∫₀¹ x²dx" },
    { id: 23, topicId: 9, title: "ផ្ទៃក្រឡា", difficulty: "medium", problem: "រកផ្ទៃក្រឡារវាង y=x² និង y=x" },
    { id: 24, topicId: 9, title: "ប្រវែងសរសៃរ", difficulty: "hard", problem: "រកប្រវែងសរសៃរ y=x²/2 ពី x=0 ដល់ x=1" },
    { id: 25, topicId: 10, title: "Differential ទី១", difficulty: "easy", problem: "ដោះស្រាយ y' = 2x" },
    { id: 26, topicId: 10, title: "Separable", difficulty: "medium", problem: "ដោះស្រាយ y' = y/x" },
    { id: 27, topicId: 10, title: "Linear", difficulty: "hard", problem: "ដោះស្រាយ y' + y = eˣ" },
    { id: 28, topicId: 11, title: "DE ទី២", difficulty: "easy", problem: "ដោះស្រាយ y'' - 4y = 0" },
    { id: 29, topicId: 11, title: "DE ទី២", difficulty: "medium", problem: "ដោះស្រាយ y'' - 3y' + 2y = 0" },
    { id: 30, topicId: 11, title: "DE ទី២ ឬសស្មុគស្មាញ", difficulty: "hard", problem: "ដោះស្រាយ y'' + 4y = 0" },
    { id: 31, topicId: 12, title: "ចម្ងាយ", difficulty: "easy", problem: "រកចម្ងាយ A(1,2,3) និង B(4,6,8)" },
    { id: 32, topicId: 12, title: "សរសៃរ", difficulty: "medium", problem: "រកសមីការសរសៃរ AB ដែល A(1,0,2) B(3,4,6)" },
    { id: 33, topicId: 12, title: "ប្លង់", difficulty: "medium", problem: "រកចម្ងាយពី (1,2,3) ទៅប្លង់ 2x + y - z = 4" },
    { id: 34, topicId: 13, title: "កំពូលប៉ារ៉ាបូល", difficulty: "easy", problem: "រកកំពូល y = x² - 6x + 8" },
    { id: 35, topicId: 13, title: "ផ្ចិតប៉ារ៉ាបូល", difficulty: "medium", problem: "រកផ្ចិត y² = 8x" },
    { id: 36, topicId: 14, title: "ឧស្សាហកម្មអេលីប", difficulty: "easy", problem: "រក e នៃ x²/16 + y²/9 = 1" },
    { id: 37, topicId: 14, title: "c នៃអេលីប", difficulty: "medium", problem: "រក c នៃ x²/25 + y²/16 = 1" },
    { id: 38, topicId: 15, title: "ឧស្សាហកម្មអ៊ីពែប៉ូល", difficulty: "easy", problem: "រក e នៃ x²/4 - y²/9 = 1" },
    { id: 39, topicId: 15, title: "អ័ក្សអាស៊ីមតូត", difficulty: "medium", problem: "រកអ័ក្សអាស៊ីមតូត x²/9 - y²/16 = 1" },
    { id: 40, topicId: 15, title: "សមីកាអ៊ីពែប៉ូល", difficulty: "hard", problem: "រកសមីកាអ៊ីពែប៉ូលដែលមានផ្ចិត (±5,0) និង e = 5/3" }
];
